### PR TITLE
chore: add guix sigs for pasta for 20.1.0

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — COMMENTED** [review]
Looks good so far

**Review by knst — COMMENTED** [review]
hashes `20.1.0/pasta/noncodesigned.SHA256SUMS` matched, gpg signature seems valid too.

Waiting for signed binaries

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by thephez — APPROVED** [review]
ACK

**Pull request merged**
