### PR TITLE
chore: signatures for 21.1.0 for knst

### PR DESCRIPTION
**Pull request by knst**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good so far

nit: commit message/pr title should say `21.1.0`, not `21.1.1` ;)

**Review by thephez — COMMENTED** [review]
Hashes match mine at 3202b945cb2be3a037888e3a6e3dd805c03c8d28

**Review by PastaPastaPasta — APPROVED** [review]
ACK

**Review by UdjinM6 — APPROVED** [review]
ACK 8700d5948eea10571830a0dfe62fbb94bb15b8c9

**Review by thephez — APPROVED** [review]
LGTM 8700d5948eea10571830a0dfe62fbb94bb15b8c9

**Pull request merged**
