### PR TITLE
chore: add guix sigs for thephez for 22.0.0-rc.1

### PR DESCRIPTION
**Pull request by thephez**
- [x] Unsigned
- [x] Signed

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hashes look good but there are too many of them, pls see https://github.com/dashpay/dash/pull/6393

**Comment by PastaPastaPasta** [comment]
It is fine to attest to more hashes no?

**Comment by UdjinM6** [comment]
It's impossible to verify extra hashes without building extra binaries too which kind of defeats the point of releasing binaries for some hosts only imo.

**Comment by PastaPastaPasta** [comment]
That's okay imo; and, for this release at least, I built all of them too and they match. But I don't really want to clutter GitHub release with SOOO many artifacts.

**Comment by PastaPastaPasta** [comment]
LGTM 1375d05a9836ec3b796b1b9c3ccdf6a0558e5c0a

**Review by UdjinM6 — APPROVED** [review]
utACK 1375d05a9836ec3b796b1b9c3ccdf6a0558e5c0a

**Review by UdjinM6 — APPROVED** [review]
utACK 11dc63ac6467c6e8308544e48902cd33f5fa5dc7

**Pull request merged**
